
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SELECT_ACTIVE_CONVERSATION = 'SELECT_ACTIVE_CONVERSATION';
export const GET_CONVERSION_MESSAGES = 'GET_CONVERSION_MESSAGES';
export const TOGGLE_ARCHIVE_USER = 'TOGGLE_ARCHIVE_USER';
export const TOGGLE_AUTH_ONLINE_STATUS = 'TOGGLE_AUTH_ONLINE_STATUS';